[config]
schemaVersion = "0.0.1"

[package]
namespace = "GravitonGamer"
name = "Upgrade_Champions_2"
versionNumber = "1.2.0"
description = "A mod for Monster Train 2 that lets you upgrade champion cards just like other unit cards."
websiteUrl = "https://github.com/Jace17/UpgradeChampions2"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.7.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


